"""Pydantic schemas — action types, validation, optional fields."""
from __future__ import annotations

import pytest
from pydantic import ValidationError

from app.schemas import Rule, RuleCreate, SubmitItem, SubmitRequest


class TestRuleSchema:
    @pytest.mark.parametrize(
        "action",
        ["reply", "flag", "discard", "label", "crm_handoff", "exclude"],
    )
    def test_all_action_types_accepted(self, action):
        r = Rule(
            id="x", name="x", filter_prompt="x", action_type=action,
        )
        assert r.action_type == action

    def test_unknown_action_rejected(self):
        with pytest.raises(ValidationError):
            Rule(id="x", name="x", filter_prompt="x", action_type="banish")

    @pytest.mark.parametrize("mode", ["draft", "send"])
    def test_send_modes_accepted(self, mode):
        r = Rule(id="x", name="x", filter_prompt="x", action_type="reply", send_mode=mode)
        assert r.send_mode == mode

    def test_unknown_send_mode_rejected(self):
        with pytest.raises(ValidationError):
            Rule(id="x", name="x", filter_prompt="x", action_type="reply", send_mode="shout")

    def test_filter_prompt_required(self):
        with pytest.raises(ValidationError):
            Rule(id="x", name="x", action_type="reply")

    def test_id_required(self):
        with pytest.raises(ValidationError):
            Rule(name="x", filter_prompt="x", action_type="reply")

    def test_defaults(self):
        r = Rule(id="x", name="x", filter_prompt="x")
        assert r.action_type == "reply"
        assert r.send_mode == "draft"
        assert r.confidence_threshold == 0.85
        assert r.enabled is True
        assert r.priority == 100
        assert r.knowledge_files == []
        assert r.voice_file is None
        assert r.reply_prompt is None
        assert r.label is None

    def test_reply_prompt_accepts_string_and_none(self):
        a = Rule(id="x", name="x", filter_prompt="x", reply_prompt="extra")
        b = Rule(id="x", name="x", filter_prompt="x", reply_prompt=None)
        assert a.reply_prompt == "extra"
        assert b.reply_prompt is None


class TestRuleCreate:
    def test_create_works_without_id(self):
        """`id` is auto-generated by the store; not part of the create payload."""
        c = RuleCreate(name="x", filter_prompt="x")
        assert "id" not in c.model_dump()

    def test_create_validates_required_fields(self):
        with pytest.raises(ValidationError):
            RuleCreate(name="x")  # missing filter_prompt


class TestSubmitItem:
    def test_minimal_submit_item(self):
        s = SubmitItem(decision_id="d-1")
        assert s.edited_draft is None
        assert s.save_to_knowledge is None

    def test_submit_item_with_overrides(self):
        s = SubmitItem(
            decision_id="d-1",
            edited_draft="edited",
            save_to_knowledge="faq.md",
        )
        assert s.edited_draft == "edited"
        assert s.save_to_knowledge == "faq.md"

    def test_submit_request_wraps_items(self):
        req = SubmitRequest(items=[SubmitItem(decision_id="a"), SubmitItem(decision_id="b")])
        assert len(req.items) == 2
